packages:
  - packages/*

allowBuilds:
  msgpackr-extract: false

catalog:
  '@biomejs/biome': 2.5.4
  '@effect/language-service': 0.87.1
  '@effect/platform': 0.97.1
  '@types/bun': 1.3.14
  '@types/node': 24.12.4
  effect: 3.22.1
  typescript: 6.0.3
