import { afterEach, beforeEach } from 'bun:test';
import { existsSync, readFileSync } from 'node:fs';
import { join, resolve as resolvePath } from 'node:path';
import { plugin } from 'bun';
import * as Cause from 'effect/Cause';
import * as Effect from 'effect/Effect';
import { resetNavigation } from './app-doubles/navigation';
import { resetPage } from './app-doubles/state';
import { registerDom, registerResetHook, resetDom } from './dom';
import { deriveBrowserSubstitutions, SUBSTITUTION_ROOTS, sveltePlugin } from './plugin';

const TESTING_LIBRARY_SPECIFIER = '@testing-library/svelte';
const SVELTE_KIT_TSCONFIG = '.svelte-kit/tsconfig.json';
const EXTENDS_PATTERN = /"extends"\s*:\s*"([^"]+)"/;

const SUBSTITUTION_FAILURE_HINT = [
  'bun-svelte-test: the svelte browser-build substitution did NOT take.',
  '',
  "Every failure mode this guards is otherwise SILENT. On svelte's server build,",
  '`flushSync`, `onMount`, `beforeUpdate` and `afterUpdate` are all the same `noop`',
  '(they do not throw, they just do nothing), and `svelte/reactivity` hands out',
  'plain `globalThis` Map/Set/Date. Tests would keep "passing" while asserting on a',
  'DOM that never updated.',
  '',
  'Likely causes:',
  '  1. svelte was upgraded and the shape of its package.json `exports` map changed.',
  '     This loader derives the substitution from that map at preload time, so a',
  '     restructured map silently yields zero substitutions.',
  '  2. Two svelte copies are installed, and the tests load a different copy than the',
  '     one substituted. Check `bun pm why svelte` from this package directory.',
  '  3. Something imported `svelte` before this preload registered the plugin.',
].join('\n');

const PARALLEL_UNSUPPORTED_HINT = [
  'bun-svelte-test: this loader does NOT support `bun test --parallel`.',
  '',
  "Detected: this preload's own module body did not run to completion before the",
  'first test executed. Under `--parallel` (measured on bun 1.3.14) everything a',
  'preload does AFTER a top-level `await` is silently abandoned — the continuation',
  'never runs at all, so every hook it would have registered is never wired.',
  '',
  'For this loader that silently discards, in order:',
  '  1. the svelte browser-build assertion — the guard proving `mount()` is not the',
  '     server no-op. Under `--parallel` that guard cannot fire even when it should.',
  "  2. `@testing-library/svelte`'s automatic render cleanup.",
  '  3. the automatic per-test reset of the DOM, storage, location and `$app` doubles.',
  '',
  'Tests then bleed into one another: `goto.mock.calls` accumulates across tests, a',
  'component mounted by one test reads a `page` a DIFFERENT test wrote, and the body',
  'is never cleared. `--parallel` additionally runs separate FILES in separate',
  'processes, so cross-file cleanup proofs cannot hold either.',
  '',
  'This failure is DELIBERATE. Without it the run stays GREEN while asserting against',
  'state that leaked from an unrelated test — silently WRONG results rather than an',
  'error. The flag is not detectable from `process.argv`/`Bun.argv` (identical with',
  'and without it), so the truncated preload is the only available signal.',
  '',
  'Fix: run these suites WITHOUT `--parallel`.',
].join('\n');

const assertSvelteKitSyncRan = (): void => {
  const tsconfigPath = join(process.cwd(), 'tsconfig.json');
  if (!existsSync(tsconfigPath)) return;

  const extendsTarget = EXTENDS_PATTERN.exec(readFileSync(tsconfigPath, 'utf8'))?.[1];
  if (extendsTarget === undefined || !extendsTarget.includes(SVELTE_KIT_TSCONFIG)) return;
  if (existsSync(resolvePath(process.cwd(), extendsTarget))) return;

  throw new Error(
    [
      `bun-svelte-test: ${tsconfigPath} extends "${extendsTarget}", but that file does not exist.`,
      '',
      'It is generated by SvelteKit and is gitignored, so a fresh checkout or a new',
      'git worktree will not have it. Without it, bun cannot resolve `$lib/*` and you',
      'will see `Cannot find module` errors that look like a loader failure.',
      '',
      'Fix: run `bunx svelte-kit sync` in this package.',
    ].join('\n'),
  );
};

const assertSvelteBrowserBuild: Effect.Effect<void> = Effect.gen(function* () {
  const svelte = yield* Effect.promise(() => import('svelte'));
  const reactivity = yield* Effect.promise(() => import('svelte/reactivity'));

  const failures: string[] = [];
  if ((svelte.flushSync as unknown) === (svelte.onMount as unknown)) {
    failures.push('  - `flushSync` and `onMount` are the SAME reference (both are the server `noop`).');
  }
  if (svelte.mount.toString().includes('lifecycle_function_unavailable')) {
    failures.push('  - `mount()` still throws `lifecycle_function_unavailable`.');
  }
  if ((reactivity.SvelteMap as unknown) === (globalThis.Map as unknown)) {
    failures.push('  - `SvelteMap` from `svelte/reactivity` IS `globalThis.Map`.');
  }
  if (failures.length === 0) return;

  const substitutions = deriveBrowserSubstitutions();
  // A preload that cannot prove the substitution took must abort the run, and a
  // defect is the Effect-native way to say "this is not recoverable": it reaches
  // the top-level `await` below as the thrown `Error` itself.
  return yield* Effect.die(
    new Error(
      [
        SUBSTITUTION_FAILURE_HINT,
        '',
        'Failed checks:',
        ...failures,
        '',
        `Derived ${substitutions.length} substitution(s) from: ${SUBSTITUTION_ROOTS.join(', ')}`,
        ...substitutions.map((s) => `  - "svelte${s.subpath.slice(1)}": ${s.serverPath} -> ${s.browserPath}`),
      ].join('\n'),
    ),
  );
});

const resolveOptionalPeer = (specifier: string): string | undefined => {
  for (const dir of [import.meta.dir, process.cwd()]) {
    try {
      return Bun.resolveSync(specifier, dir);
    } catch {}
  }
  return undefined;
};

const wireTestingLibrary: Effect.Effect<void> = Effect.gen(function* () {
  const resolved = resolveOptionalPeer(TESTING_LIBRARY_SPECIFIER);
  if (resolved === undefined) return;

  // `Effect.promise` surfaces a rejected import as a defect, so `catchCause`
  // replaces v3's `try`/`catch` and `Cause.squash` recovers the original reason
  // to hang off `cause`.
  yield* Effect.promise(() => import(resolved)).pipe(
    Effect.catchCause((cause) =>
      Effect.die(
        new Error(
          [
            `bun-svelte-test: \`${TESTING_LIBRARY_SPECIFIER}\` is installed (resolved to ${resolved})`,
            'but failed to import during preload, so its automatic render cleanup is NOT wired.',
            'Tests would leak mounted components into each other.',
            '',
            'Note: do NOT import `@testing-library/svelte/vitest` — that subpath imports',
            '`beforeEach` from vitest, which does not exist under bun.',
          ].join('\n'),
          { cause: Cause.squash(cause) },
        ),
      ),
    ),
  );
});

assertSvelteKitSyncRan();

registerDom();

plugin(sveltePlugin);

let preloadCompleted = false;

beforeEach(() => {
  if (!preloadCompleted) throw new Error(PARALLEL_UNSUPPORTED_HINT);
});

await Effect.runPromise(assertSvelteBrowserBuild);

await Effect.runPromise(wireTestingLibrary);

registerResetHook(resetNavigation);
registerResetHook(resetPage);
afterEach(() => {
  resetDom();
});

preloadCompleted = true;
